//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Almacen
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Almacen()
    {
        this.InventarioFisico = new HashSet<InventarioFisico>();
        this.RemisionEntrada = new HashSet<RemisionEntrada>();
    }

    public int Id { get; set; }
    public string Codigo { get; set; }
    public string Nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<InventarioFisico> InventarioFisico { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RemisionEntrada> RemisionEntrada { get; set; }
}

public partial class InventarioFisico
{
    public int Id { get; set; }
    public int IdAlmacen { get; set; }
    public int IdProducto { get; set; }
    public int Cantidad { get; set; }

    public virtual Almacen Almacen { get; set; }
    public virtual Producto Producto { get; set; }
}

public partial class Producto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Producto()
    {
        this.InventarioFisico = new HashSet<InventarioFisico>();
        this.RemisionEntradaDetalle = new HashSet<RemisionEntradaDetalle>();
    }

    public int Id { get; set; }
    public string Codigo { get; set; }
    public string Nombre { get; set; }
    public string Descripcion { get; set; }
    public decimal PrecioVenta { get; set; }
    public int StockMinimo { get; set; }
    public int StockMaximo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<InventarioFisico> InventarioFisico { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RemisionEntradaDetalle> RemisionEntradaDetalle { get; set; }
}

public partial class Proveedor
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Proveedor()
    {
        this.RemisionEntrada = new HashSet<RemisionEntrada>();
    }

    public int Id { get; set; }
    public string Codigo { get; set; }
    public string Nombre { get; set; }
    public string Direccion { get; set; }
    public string Telefono { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RemisionEntrada> RemisionEntrada { get; set; }
}

public partial class RemisionEntrada
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RemisionEntrada()
    {
        this.RemisionEntradaDetalle = new HashSet<RemisionEntradaDetalle>();
    }

    public int Id { get; set; }
    public string Codigo { get; set; }
    public System.DateTime FechaDocumento { get; set; }
    public int IdProveedor { get; set; }
    public int IdAlmacen { get; set; }
    public int Estado { get; set; }

    public virtual Almacen Almacen { get; set; }
    public virtual Proveedor Proveedor { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RemisionEntradaDetalle> RemisionEntradaDetalle { get; set; }
}

public partial class RemisionEntradaDetalle
{
    public int Id { get; set; }
    public int IdRemisionEntrada { get; set; }
    public int IdProducto { get; set; }
    public int Cantidad { get; set; }

    public virtual Producto Producto { get; set; }
    public virtual RemisionEntrada RemisionEntrada { get; set; }
}

public partial class SearchAllRemisionEntrada_Result
{
    public int Id { get; set; }
    public string Codigo { get; set; }
    public string Provedor { get; set; }
    public string Almacen { get; set; }
    public string Estado { get; set; }
}

public partial class SearchProductoYRemisionEntrada_Result
{
    public int Id { get; set; }
    public int IdRemisionEntrada { get; set; }
    public int IdProducto { get; set; }
    public int Cantidad { get; set; }
}
