//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class indigoDBEntities : DbContext
    {
        public indigoDBEntities()
            : base("name=indigoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<InventarioFisico> InventarioFisico { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<RemisionEntrada> RemisionEntrada { get; set; }
        public virtual DbSet<RemisionEntradaDetalle> RemisionEntradaDetalle { get; set; }
    
        public virtual ObjectResult<SearchAllProveedores_Result> SearchAllProveedores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllProveedores_Result>("SearchAllProveedores");
        }
    
        public virtual ObjectResult<SearchAllProductos_Result> SearchAllProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllProductos_Result>("SearchAllProductos");
        }
    
        public virtual ObjectResult<SearchAllProveedores1_Result> SearchAllProveedores1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllProveedores1_Result>("SearchAllProveedores1");
        }
    
        public virtual ObjectResult<SearchAllProductos1_Result> SearchAllProductos1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllProductos1_Result>("SearchAllProductos1");
        }
    
        public virtual ObjectResult<SearchAllRemisionEntrada_Result> SearchAllRemisionEntrada()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllRemisionEntrada_Result>("SearchAllRemisionEntrada");
        }
    
        public virtual ObjectResult<SearchAllRemisionEntrada1_Result> SearchAllRemisionEntrada1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllRemisionEntrada1_Result>("SearchAllRemisionEntrada1");
        }
    
        public virtual ObjectResult<SearchAllRemisionEntradaDetalle_Result> SearchAllRemisionEntradaDetalle(Nullable<int> idEntradaDetalle)
        {
            var idEntradaDetalleParameter = idEntradaDetalle.HasValue ?
                new ObjectParameter("idEntradaDetalle", idEntradaDetalle) :
                new ObjectParameter("idEntradaDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllRemisionEntradaDetalle_Result>("SearchAllRemisionEntradaDetalle", idEntradaDetalleParameter);
        }
    
        public virtual ObjectResult<SearchAllRemisionEntradaD_Result> SearchAllRemisionEntradaD(Nullable<int> idEntradaDetalle)
        {
            var idEntradaDetalleParameter = idEntradaDetalle.HasValue ?
                new ObjectParameter("idEntradaDetalle", idEntradaDetalle) :
                new ObjectParameter("idEntradaDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllRemisionEntradaD_Result>("SearchAllRemisionEntradaD", idEntradaDetalleParameter);
        }
    
        public virtual ObjectResult<SearchAllRemisionEntradaByDetalle_Result> SearchAllRemisionEntradaByDetalle(Nullable<int> idEntradaDetalle)
        {
            var idEntradaDetalleParameter = idEntradaDetalle.HasValue ?
                new ObjectParameter("idEntradaDetalle", idEntradaDetalle) :
                new ObjectParameter("idEntradaDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllRemisionEntradaByDetalle_Result>("SearchAllRemisionEntradaByDetalle", idEntradaDetalleParameter);
        }
    
        public virtual ObjectResult<SearchAllRemisionEntradaDetalleByRemision_Result> SearchAllRemisionEntradaDetalleByRemision(Nullable<int> idEntradaDetalle)
        {
            var idEntradaDetalleParameter = idEntradaDetalle.HasValue ?
                new ObjectParameter("idEntradaDetalle", idEntradaDetalle) :
                new ObjectParameter("idEntradaDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllRemisionEntradaDetalleByRemision_Result>("SearchAllRemisionEntradaDetalleByRemision", idEntradaDetalleParameter);
        }
    
        public virtual ObjectResult<SearchAllRemisionEntradaDetalleByRIdRemisionEntrada_Result> SearchAllRemisionEntradaDetalleByRIdRemisionEntrada(Nullable<int> idEntradaDetalle)
        {
            var idEntradaDetalleParameter = idEntradaDetalle.HasValue ?
                new ObjectParameter("idEntradaDetalle", idEntradaDetalle) :
                new ObjectParameter("idEntradaDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllRemisionEntradaDetalleByRIdRemisionEntrada_Result>("SearchAllRemisionEntradaDetalleByRIdRemisionEntrada", idEntradaDetalleParameter);
        }
    
        public virtual ObjectResult<SearchProductoYRemisionEntrada_Result> SearchProductoYRemisionEntrada(Nullable<int> idEntradaDetalle, Nullable<int> idProducto)
        {
            var idEntradaDetalleParameter = idEntradaDetalle.HasValue ?
                new ObjectParameter("idEntradaDetalle", idEntradaDetalle) :
                new ObjectParameter("idEntradaDetalle", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchProductoYRemisionEntrada_Result>("SearchProductoYRemisionEntrada", idEntradaDetalleParameter, idProductoParameter);
        }
    
        public virtual ObjectResult<Report1_Result> Report1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report1_Result>("Report1");
        }
    
        public virtual ObjectResult<SearchInventarioFisicoCantidad_Result> SearchInventarioFisicoCantidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchInventarioFisicoCantidad_Result>("SearchInventarioFisicoCantidad");
        }
    }
}
