//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaCliente.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarProveedor", ReplyAction="http://tempuri.org/IService/agregarProveedorResponse")]
        void agregarProveedor(string Codigo, string Nombre, string Direccion, string Telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarProveedor", ReplyAction="http://tempuri.org/IService/agregarProveedorResponse")]
        System.Threading.Tasks.Task agregarProveedorAsync(string Codigo, string Nombre, string Direccion, string Telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateProveedor", ReplyAction="http://tempuri.org/IService/updateProveedorResponse")]
        void updateProveedor(System.Nullable<int> id, string Codigo, string Nombre, string Direccion, string Telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateProveedor", ReplyAction="http://tempuri.org/IService/updateProveedorResponse")]
        System.Threading.Tasks.Task updateProveedorAsync(System.Nullable<int> id, string Codigo, string Nombre, string Direccion, string Telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteProveedor", ReplyAction="http://tempuri.org/IService/deleteProveedorResponse")]
        void deleteProveedor(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteProveedor", ReplyAction="http://tempuri.org/IService/deleteProveedorResponse")]
        System.Threading.Tasks.Task deleteProveedorAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarProducto", ReplyAction="http://tempuri.org/IService/agregarProductoResponse")]
        void agregarProducto(string Codigo, string Nombre, string Descripcion, decimal PrecioVenta, int StockMinimo, int StockMaximo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarProducto", ReplyAction="http://tempuri.org/IService/agregarProductoResponse")]
        System.Threading.Tasks.Task agregarProductoAsync(string Codigo, string Nombre, string Descripcion, decimal PrecioVenta, int StockMinimo, int StockMaximo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateProducto", ReplyAction="http://tempuri.org/IService/updateProductoResponse")]
        void updateProducto(System.Nullable<int> id, string Codigo, string Nombre, string Descripcion, decimal PrecioVenta, int StockMinimo, int StockMaximo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateProducto", ReplyAction="http://tempuri.org/IService/updateProductoResponse")]
        System.Threading.Tasks.Task updateProductoAsync(System.Nullable<int> id, string Codigo, string Nombre, string Descripcion, decimal PrecioVenta, int StockMinimo, int StockMaximo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteProducto", ReplyAction="http://tempuri.org/IService/deleteProductoResponse")]
        void deleteProducto(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteProducto", ReplyAction="http://tempuri.org/IService/deleteProductoResponse")]
        System.Threading.Tasks.Task deleteProductoAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarRemision", ReplyAction="http://tempuri.org/IService/agregarRemisionResponse")]
        void agregarRemision(string Codigo, int idProveedor, int idAlmacen, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarRemision", ReplyAction="http://tempuri.org/IService/agregarRemisionResponse")]
        System.Threading.Tasks.Task agregarRemisionAsync(string Codigo, int idProveedor, int idAlmacen, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateRemision", ReplyAction="http://tempuri.org/IService/updateRemisionResponse")]
        void updateRemision(System.Nullable<int> id, string Codigo, int idProveedor, int idAlmacen, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateRemision", ReplyAction="http://tempuri.org/IService/updateRemisionResponse")]
        System.Threading.Tasks.Task updateRemisionAsync(System.Nullable<int> id, string Codigo, int idProveedor, int idAlmacen, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteRemision", ReplyAction="http://tempuri.org/IService/deleteRemisionResponse")]
        void deleteRemision(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteRemision", ReplyAction="http://tempuri.org/IService/deleteRemisionResponse")]
        System.Threading.Tasks.Task deleteRemisionAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarRemisionDetalle", ReplyAction="http://tempuri.org/IService/agregarRemisionDetalleResponse")]
        void agregarRemisionDetalle(int idRemisionEntrada, int idProducto, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarRemisionDetalle", ReplyAction="http://tempuri.org/IService/agregarRemisionDetalleResponse")]
        System.Threading.Tasks.Task agregarRemisionDetalleAsync(int idRemisionEntrada, int idProducto, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateRemisionDetalle", ReplyAction="http://tempuri.org/IService/updateRemisionDetalleResponse")]
        void updateRemisionDetalle(System.Nullable<int> id, int idRemisionEntrada, int idProducto, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateRemisionDetalle", ReplyAction="http://tempuri.org/IService/updateRemisionDetalleResponse")]
        System.Threading.Tasks.Task updateRemisionDetalleAsync(System.Nullable<int> id, int idRemisionEntrada, int idProducto, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteRemisionDetalle", ReplyAction="http://tempuri.org/IService/deleteRemisionDetalleResponse")]
        void deleteRemisionDetalle(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/deleteRemisionDetalle", ReplyAction="http://tempuri.org/IService/deleteRemisionDetalleResponse")]
        System.Threading.Tasks.Task deleteRemisionDetalleAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/inventarioFisico", ReplyAction="http://tempuri.org/IService/inventarioFisicoResponse")]
        void inventarioFisico(int id, int Almacen, int producto, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/inventarioFisico", ReplyAction="http://tempuri.org/IService/inventarioFisicoResponse")]
        System.Threading.Tasks.Task inventarioFisicoAsync(int id, int Almacen, int producto, int cantidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CapaCliente.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CapaCliente.ServiceReference1.IService>, CapaCliente.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void agregarProveedor(string Codigo, string Nombre, string Direccion, string Telefono) {
            base.Channel.agregarProveedor(Codigo, Nombre, Direccion, Telefono);
        }
        
        public System.Threading.Tasks.Task agregarProveedorAsync(string Codigo, string Nombre, string Direccion, string Telefono) {
            return base.Channel.agregarProveedorAsync(Codigo, Nombre, Direccion, Telefono);
        }
        
        public void updateProveedor(System.Nullable<int> id, string Codigo, string Nombre, string Direccion, string Telefono) {
            base.Channel.updateProveedor(id, Codigo, Nombre, Direccion, Telefono);
        }
        
        public System.Threading.Tasks.Task updateProveedorAsync(System.Nullable<int> id, string Codigo, string Nombre, string Direccion, string Telefono) {
            return base.Channel.updateProveedorAsync(id, Codigo, Nombre, Direccion, Telefono);
        }
        
        public void deleteProveedor(System.Nullable<int> id) {
            base.Channel.deleteProveedor(id);
        }
        
        public System.Threading.Tasks.Task deleteProveedorAsync(System.Nullable<int> id) {
            return base.Channel.deleteProveedorAsync(id);
        }
        
        public void agregarProducto(string Codigo, string Nombre, string Descripcion, decimal PrecioVenta, int StockMinimo, int StockMaximo) {
            base.Channel.agregarProducto(Codigo, Nombre, Descripcion, PrecioVenta, StockMinimo, StockMaximo);
        }
        
        public System.Threading.Tasks.Task agregarProductoAsync(string Codigo, string Nombre, string Descripcion, decimal PrecioVenta, int StockMinimo, int StockMaximo) {
            return base.Channel.agregarProductoAsync(Codigo, Nombre, Descripcion, PrecioVenta, StockMinimo, StockMaximo);
        }
        
        public void updateProducto(System.Nullable<int> id, string Codigo, string Nombre, string Descripcion, decimal PrecioVenta, int StockMinimo, int StockMaximo) {
            base.Channel.updateProducto(id, Codigo, Nombre, Descripcion, PrecioVenta, StockMinimo, StockMaximo);
        }
        
        public System.Threading.Tasks.Task updateProductoAsync(System.Nullable<int> id, string Codigo, string Nombre, string Descripcion, decimal PrecioVenta, int StockMinimo, int StockMaximo) {
            return base.Channel.updateProductoAsync(id, Codigo, Nombre, Descripcion, PrecioVenta, StockMinimo, StockMaximo);
        }
        
        public void deleteProducto(System.Nullable<int> id) {
            base.Channel.deleteProducto(id);
        }
        
        public System.Threading.Tasks.Task deleteProductoAsync(System.Nullable<int> id) {
            return base.Channel.deleteProductoAsync(id);
        }
        
        public void agregarRemision(string Codigo, int idProveedor, int idAlmacen, int estado) {
            base.Channel.agregarRemision(Codigo, idProveedor, idAlmacen, estado);
        }
        
        public System.Threading.Tasks.Task agregarRemisionAsync(string Codigo, int idProveedor, int idAlmacen, int estado) {
            return base.Channel.agregarRemisionAsync(Codigo, idProveedor, idAlmacen, estado);
        }
        
        public void updateRemision(System.Nullable<int> id, string Codigo, int idProveedor, int idAlmacen, int estado) {
            base.Channel.updateRemision(id, Codigo, idProveedor, idAlmacen, estado);
        }
        
        public System.Threading.Tasks.Task updateRemisionAsync(System.Nullable<int> id, string Codigo, int idProveedor, int idAlmacen, int estado) {
            return base.Channel.updateRemisionAsync(id, Codigo, idProveedor, idAlmacen, estado);
        }
        
        public void deleteRemision(System.Nullable<int> id) {
            base.Channel.deleteRemision(id);
        }
        
        public System.Threading.Tasks.Task deleteRemisionAsync(System.Nullable<int> id) {
            return base.Channel.deleteRemisionAsync(id);
        }
        
        public void agregarRemisionDetalle(int idRemisionEntrada, int idProducto, int cantidad) {
            base.Channel.agregarRemisionDetalle(idRemisionEntrada, idProducto, cantidad);
        }
        
        public System.Threading.Tasks.Task agregarRemisionDetalleAsync(int idRemisionEntrada, int idProducto, int cantidad) {
            return base.Channel.agregarRemisionDetalleAsync(idRemisionEntrada, idProducto, cantidad);
        }
        
        public void updateRemisionDetalle(System.Nullable<int> id, int idRemisionEntrada, int idProducto, int cantidad) {
            base.Channel.updateRemisionDetalle(id, idRemisionEntrada, idProducto, cantidad);
        }
        
        public System.Threading.Tasks.Task updateRemisionDetalleAsync(System.Nullable<int> id, int idRemisionEntrada, int idProducto, int cantidad) {
            return base.Channel.updateRemisionDetalleAsync(id, idRemisionEntrada, idProducto, cantidad);
        }
        
        public void deleteRemisionDetalle(System.Nullable<int> id) {
            base.Channel.deleteRemisionDetalle(id);
        }
        
        public System.Threading.Tasks.Task deleteRemisionDetalleAsync(System.Nullable<int> id) {
            return base.Channel.deleteRemisionDetalleAsync(id);
        }
        
        public void inventarioFisico(int id, int Almacen, int producto, int cantidad) {
            base.Channel.inventarioFisico(id, Almacen, producto, cantidad);
        }
        
        public System.Threading.Tasks.Task inventarioFisicoAsync(int id, int Almacen, int producto, int cantidad) {
            return base.Channel.inventarioFisicoAsync(id, Almacen, producto, cantidad);
        }
    }
}
